services:
  - type: web
    name: bird-species-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: MODEL_PATH
        value: model/bird_classifier.onnx
      - key: LABELS_PATH
        value: model/bird_labels.txt
      - key: PYTHON_VERSION
        value: 3.9.0